name: Deploy application

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: frostiiz-runner
    steps:
      - name: Deploy Laevatin bot
        uses: appleboy/ssh-action
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: whoami
