name: Deploy Laevatin bot
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build
    runs-on: frostiiz-runner
    steps:
      - name: SSH cloning repo & installing dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LAEVATEIN_HOST }}
          port: ${{ secrets.LAEVATEIN_PORT }}
          username: ${{ secrets.LAEVATEIN_USER }}
          key: ${{ secrets.LAEVATEIN_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd laevatein/
            git pull
            npm i
