name: Deploy application

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: frostiiz-runner
    steps:
      - name: Deploy Laevatin bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: whoami
