name: Deploy Laevatin bot
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build
    runs-on: frostiiz-runner
    steps:
      - name: Executing command via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LAEVATEIN_HOST }}
          username: ${{ secrets.LAEVATEIN_USERNAME }}
          password: ${{ secrets.LAEVATEIN_PASSWORD }}
          port: ${{ secrets.LAEVATEIN_PORT }}
          script: whoami
