name: Deploy application

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Laevatin bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LAEVATEIN_HOST }}
          username: ${{ secrets.LAEVATEIN_USERNAME }}
          key: ${{ secrets.LAEVATEIN_KEY }}
          port: ${{ secrets.LAEVATEIN_PORT }}
          script: |
            git clone git@github.com:FrostiizGit/laevatein.git
            cd laevatein # navigate into the repo
            npm install # install dependencies
