name: Deploy Laevatin bot
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build
    runs-on: frostiiz-runner
    steps:
      - name: SSH cloning repo & installing dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LAEVATEIN_HOST }}
          port: ${{ secrets.LAEVATEIN_PORT }}
          username: ${{ secrets.LAEVATEIN_USER }}
          key: ${{ secrets.LAEVATEIN_KEY }}
          script: |
            git clone git@github.com:FrostiizGit/laevatein.git # clone the repo into the 'app' folder
            cd laevatein # navigate into the repo
            npm install # install dependencies
