name: Deploy application

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: frostiiz-runner
    steps:
      - name: Deploy Laevatin bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            git clone git@github.com:FrostiizGit/laevatein.git
            cd laevatein # navigate into the repo
            npm install # install dependencies
